/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BEAN.Producto;
import DAO.ProductoDAO;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James
 */
public class selProductos extends javax.swing.JDialog {

    /**
     * Creates new form selProductos
     */
    DefaultTableModel dtm;
    ProductoDAO proDAO;
    Producto pro;
    public selProductos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pro = new Producto();
        proDAO = new ProductoDAO();
        dtm = (DefaultTableModel) this.tblInsumo.getModel();
        llenatblProducto(false, "");
    }
    
    private void llenatblProducto(boolean sw, String Cod) {
        Vector<Producto> listaPro;
        listaPro = proDAO.listaProductos(sw, Cod);
        dtm.setRowCount(0);
        for (int i = 0; i < listaPro.size(); i++)
        {
            Vector vec = new Vector();
            vec.addElement(listaPro.get(i).getIdProducto());
            vec.addElement(listaPro.get(i).getNombreProducto());
            dtm.addRow(vec);
        }

    }
    public Producto getPro() {
        return pro;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsumo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        tblInsumo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdProducto", "Nombre"
            }
        ));
        tblInsumo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInsumoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInsumo);

        jLabel2.setText("BUSCUEDA DE PRODUCTOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        // TODO add your handling code here:
        if (this.txtBuscar.getText().isEmpty())
        {
            llenatblProducto(false, "");
        } else
        {
            llenatblProducto(true, this.txtBuscar.getText());
        }
        int idi;
        idi = this.tblInsumo.getSelectedRow();
        pro.setIdProducto(Integer.parseInt(dtm.getValueAt(idi, 0).toString()));
        pro.setNombreProducto(dtm.getValueAt(idi, 1).toString());

        this.dispose();
    }//GEN-LAST:event_txtBuscarKeyReleased

    private void tblInsumoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInsumoMouseClicked
        // TODO add your handling code here:
        int i;
        i = this.tblInsumo.getSelectedRow();
        pro.setIdProducto(Integer.parseInt(dtm.getValueAt(i, 0).toString()));
        pro.setNombreProducto(dtm.getValueAt(i, 1).toString());

        this.dispose();
    }//GEN-LAST:event_tblInsumoMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInsumo;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
